class PngIcons {
  PngIcons._();

  static const featuredLgBrandDark = 'assets/icons/png/Featured/Size=lg, Color=Brand, Type=Dark.png';
  static const featuredLgBrandGlass = 'assets/icons/png/Featured/Size=lg, Color=Brand, Type=Glass.png';
  static const featuredLgBrandGradient = 'assets/icons/png/Featured/Size=lg, Color=Brand, Type=Gradient.png';
  static const featuredLgBrandLight = 'assets/icons/png/Featured/Size=lg, Color=Brand, Type=Light.png';
  static const featuredLgErrorDark = 'assets/icons/png/Featured/Size=lg, Color=Error, Type=Dark.png';
  static const featuredLgErrorGradient = 'assets/icons/png/Featured/Size=lg, Color=Error, Type=Gradient.png';
  static const featuredLgErrorLight = 'assets/icons/png/Featured/Size=lg, Color=Error, Type=Light.png';
  static const featuredLgGrayDark = 'assets/icons/png/Featured/Size=lg, Color=Gray, Type=Dark.png';
  static const featuredLgGrayGradient = 'assets/icons/png/Featured/Size=lg, Color=Gray, Type=Gradient.png';
  static const featuredLgGrayLight = 'assets/icons/png/Featured/Size=lg, Color=Gray, Type=Light.png';
  static const featuredLgGrayModern = 'assets/icons/png/Featured/Size=lg, Color=Gray, Type=Modern.png';
  static const featuredLgSuccessDark = 'assets/icons/png/Featured/Size=lg, Color=Success, Type=Dark.png';
  static const featuredLgSuccessGradient = 'assets/icons/png/Featured/Size=lg, Color=Success, Type=Gradient.png';
  static const featuredLgSuccessLight = 'assets/icons/png/Featured/Size=lg, Color=Success, Type=Light.png';
  static const featuredLgWarningDark = 'assets/icons/png/Featured/Size=lg, Color=Warning, Type=Dark.png';
  static const featuredLgWarningGradient = 'assets/icons/png/Featured/Size=lg, Color=Warning, Type=Gradient.png';
  static const featuredLgWarningLight = 'assets/icons/png/Featured/Size=lg, Color=Warning, Type=Light.png';
  static const featuredMdBrandDark = 'assets/icons/png/Featured/Size=md, Color=Brand, Type=Dark.png';
  static const featuredMdBrandGlass = 'assets/icons/png/Featured/Size=md, Color=Brand, Type=Glass.png';
  static const featuredMdBrandGradient = 'assets/icons/png/Featured/Size=md, Color=Brand, Type=Gradient.png';
  static const featuredMdBrandLight = 'assets/icons/png/Featured/Size=md, Color=Brand, Type=Light.png';
  static const featuredMdErrorDark = 'assets/icons/png/Featured/Size=md, Color=Error, Type=Dark.png';
  static const featuredMdErrorGradient = 'assets/icons/png/Featured/Size=md, Color=Error, Type=Gradient.png';
  static const featuredMdErrorLight = 'assets/icons/png/Featured/Size=md, Color=Error, Type=Light.png';
  static const featuredMdGrayDark = 'assets/icons/png/Featured/Size=md, Color=Gray, Type=Dark.png';
  static const featuredMdGrayGradient = 'assets/icons/png/Featured/Size=md, Color=Gray, Type=Gradient.png';
  static const featuredMdGrayLight = 'assets/icons/png/Featured/Size=md, Color=Gray, Type=Light.png';
  static const featuredMdGrayModern = 'assets/icons/png/Featured/Size=md, Color=Gray, Type=Modern.png';
  static const featuredMdSuccessDark = 'assets/icons/png/Featured/Size=md, Color=Success, Type=Dark.png';
  static const featuredMdSuccessGradient = 'assets/icons/png/Featured/Size=md, Color=Success, Type=Gradient.png';
  static const featuredMdSuccessLight = 'assets/icons/png/Featured/Size=md, Color=Success, Type=Light.png';
  static const featuredMdWarningDark = 'assets/icons/png/Featured/Size=md, Color=Warning, Type=Dark.png';
  static const featuredMdWarningGradient = 'assets/icons/png/Featured/Size=md, Color=Warning, Type=Gradient.png';
  static const featuredMdWarningLight = 'assets/icons/png/Featured/Size=md, Color=Warning, Type=Light.png';
  static const featuredSmBrandDark = 'assets/icons/png/Featured/Size=sm, Color=Brand, Type=Dark.png';
  static const featuredSmBrandGlass = 'assets/icons/png/Featured/Size=sm, Color=Brand, Type=Glass.png';
  static const featuredSmBrandGradient = 'assets/icons/png/Featured/Size=sm, Color=Brand, Type=Gradient.png';
  static const featuredSmBrandLight = 'assets/icons/png/Featured/Size=sm, Color=Brand, Type=Light.png';
  static const featuredSmErrorDark = 'assets/icons/png/Featured/Size=sm, Color=Error, Type=Dark.png';
  static const featuredSmErrorGradient = 'assets/icons/png/Featured/Size=sm, Color=Error, Type=Gradient.png';
  static const featuredSmErrorLight = 'assets/icons/png/Featured/Size=sm, Color=Error, Type=Light.png';
  static const featuredSmGrayDark = 'assets/icons/png/Featured/Size=sm, Color=Gray, Type=Dark.png';
  static const featuredSmGrayGradient = 'assets/icons/png/Featured/Size=sm, Color=Gray, Type=Gradient.png';
  static const featuredSmGrayLight = 'assets/icons/png/Featured/Size=sm, Color=Gray, Type=Light.png';
  static const featuredSmGrayModern = 'assets/icons/png/Featured/Size=sm, Color=Gray, Type=Modern.png';
  static const featuredSmSuccessDark = 'assets/icons/png/Featured/Size=sm, Color=Success, Type=Dark.png';
  static const featuredSmSuccessGradient = 'assets/icons/png/Featured/Size=sm, Color=Success, Type=Gradient.png';
  static const featuredSmSuccessLight = 'assets/icons/png/Featured/Size=sm, Color=Success, Type=Light.png';
  static const featuredSmWarningDark = 'assets/icons/png/Featured/Size=sm, Color=Warning, Type=Dark.png';
  static const featuredSmWarningGradient = 'assets/icons/png/Featured/Size=sm, Color=Warning, Type=Gradient.png';
  static const featuredSmWarningLight = 'assets/icons/png/Featured/Size=sm, Color=Warning, Type=Light.png';
  static const featuredXlBrandDark = 'assets/icons/png/Featured/Size=xl, Color=Brand, Type=Dark.png';
  static const featuredXlBrandGlass = 'assets/icons/png/Featured/Size=xl, Color=Brand, Type=Glass.png';
  static const featuredXlBrandGradient = 'assets/icons/png/Featured/Size=xl, Color=Brand, Type=Gradient.png';
  static const featuredXlBrandLight = 'assets/icons/png/Featured/Size=xl, Color=Brand, Type=Light.png';
  static const featuredXlErrorDark = 'assets/icons/png/Featured/Size=xl, Color=Error, Type=Dark.png';
  static const featuredXlErrorGradient = 'assets/icons/png/Featured/Size=xl, Color=Error, Type=Gradient.png';
  static const featuredXlErrorLight = 'assets/icons/png/Featured/Size=xl, Color=Error, Type=Light.png';
  static const featuredXlGrayDark = 'assets/icons/png/Featured/Size=xl, Color=Gray, Type=Dark.png';
  static const featuredXlGrayGradient = 'assets/icons/png/Featured/Size=xl, Color=Gray, Type=Gradient.png';
  static const featuredXlGrayLight = 'assets/icons/png/Featured/Size=xl, Color=Gray, Type=Light.png';
  static const featuredXlGrayModern = 'assets/icons/png/Featured/Size=xl, Color=Gray, Type=Modern.png';
  static const featuredXlSuccessDark = 'assets/icons/png/Featured/Size=xl, Color=Success, Type=Dark.png';
  static const featuredXlSuccessGradient = 'assets/icons/png/Featured/Size=xl, Color=Success, Type=Gradient.png';
  static const featuredXlSuccessLight = 'assets/icons/png/Featured/Size=xl, Color=Success, Type=Light.png';
  static const featuredXlWarningDark = 'assets/icons/png/Featured/Size=xl, Color=Warning, Type=Dark.png';
  static const featuredXlWarningGradient = 'assets/icons/png/Featured/Size=xl, Color=Warning, Type=Gradient.png';
  static const featuredXlWarningLight = 'assets/icons/png/Featured/Size=xl, Color=Warning, Type=Light.png';
  static const fileTypeArchiveRarDefault = 'assets/icons/png/File type/Archive/RAR, Type=Default.png';
  static const fileTypeArchiveRarGray = 'assets/icons/png/File type/Archive/RAR, Type=Gray.png';
  static const fileTypeArchiveRarSolid = 'assets/icons/png/File type/Archive/RAR, Type=Solid.png';
  static const fileTypeArchiveZipDefault = 'assets/icons/png/File type/Archive/ZIP, Type=Default.png';
  static const fileTypeArchiveZipGray = 'assets/icons/png/File type/Archive/ZIP, Type=Gray.png';
  static const fileTypeArchiveZipSolid = 'assets/icons/png/File type/Archive/ZIP, Type=Solid.png';
  static const fileTypeDefaultAudioGray = 'assets/icons/png/File type/Default/Audio, Type=Gray.png';
  static const fileTypeDefaultAudioSolid = 'assets/icons/png/File type/Default/Audio, Type=Solid.png';
  static const fileTypeDefaultCodeGray = 'assets/icons/png/File type/Default/Code, Type=Gray.png';
  static const fileTypeDefaultCodeSolid = 'assets/icons/png/File type/Default/Code, Type=Solid.png';
  static const fileTypeDefaultDocumentGray = 'assets/icons/png/File type/Default/Document, Type=Gray.png';
  static const fileTypeDefaultDocumentSolid = 'assets/icons/png/File type/Default/Document, Type=Solid.png';
  static const fileTypeDefaultImageGray = 'assets/icons/png/File type/Default/Image, Type=Gray.png';
  static const fileTypeDefaultImageSolid = 'assets/icons/png/File type/Default/Image, Type=Solid.png';
  static const fileTypeDefaultPdfGray = 'assets/icons/png/File type/Default/PDF, Type=Gray.png';
  static const fileTypeDefaultPdfSolid = 'assets/icons/png/File type/Default/PDF, Type=Solid.png';
  static const fileTypeDefaultSpreadsheetGray = 'assets/icons/png/File type/Default/Spreadsheet, Type=Gray.png';
  static const fileTypeDefaultSpreadsheetSolid = 'assets/icons/png/File type/Default/Spreadsheet, Type=Solid.png';
  static const fileTypeDefaultVideo01Gray = 'assets/icons/png/File type/Default/Video 01, Type=Gray.png';
  static const fileTypeDefaultVideo01Solid = 'assets/icons/png/File type/Default/Video 01, Type=Solid.png';
  static const fileTypeDefaultVideo02Gray = 'assets/icons/png/File type/Default/Video 02, Type=Gray.png';
  static const fileTypeDefaultVideo02Solid = 'assets/icons/png/File type/Default/Video 02, Type=Solid.png';
  static const fileTypeDesignAepAfterEffectsDefault = 'assets/icons/png/File type/Design/AEP (After Effects), Type=Default.png';
  static const fileTypeDesignAepAfterEffectsGray = 'assets/icons/png/File type/Design/AEP (After Effects), Type=Gray.png';
  static const fileTypeDesignAepAfterEffectsSolid = 'assets/icons/png/File type/Design/AEP (After Effects), Type=Solid.png';
  static const fileTypeDesignAiIllustratorDefault = 'assets/icons/png/File type/Design/AI (Illustrator), Type=Default.png';
  static const fileTypeDesignAiIllustratorGray = 'assets/icons/png/File type/Design/AI (Illustrator), Type=Gray.png';
  static const fileTypeDesignAiIllustratorSolid = 'assets/icons/png/File type/Design/AI (Illustrator), Type=Solid.png';
  static const fileTypeDesignFigFigmaDefault = 'assets/icons/png/File type/Design/FIG (Figma), Type=Default.png';
  static const fileTypeDesignFigFigmaGray = 'assets/icons/png/File type/Design/FIG (Figma), Type=Gray.png';
  static const fileTypeDesignFigFigmaSolid = 'assets/icons/png/File type/Design/FIG (Figma), Type=Solid.png';
  static const fileTypeDesignInddIndesignDefault = 'assets/icons/png/File type/Design/INDD (InDesign), Type=Default.png';
  static const fileTypeDesignInddIndesignGray = 'assets/icons/png/File type/Design/INDD (InDesign), Type=Gray.png';
  static const fileTypeDesignInddIndesignSolid = 'assets/icons/png/File type/Design/INDD (InDesign), Type=Solid.png';
  static const fileTypeDesignPsdPhotoshopDefault = 'assets/icons/png/File type/Design/PSD (Photoshop), Type=Default.png';
  static const fileTypeDesignPsdPhotoshopGray = 'assets/icons/png/File type/Design/PSD (Photoshop), Type=Gray.png';
  static const fileTypeDesignPsdPhotoshopSolid = 'assets/icons/png/File type/Design/PSD (Photoshop), Type=Solid.png';
  static const fileTypeDevelopmentCssDefault = 'assets/icons/png/File type/Development/CSS, Type=Default.png';
  static const fileTypeDevelopmentCssGray = 'assets/icons/png/File type/Development/CSS, Type=Gray.png';
  static const fileTypeDevelopmentCssSolid = 'assets/icons/png/File type/Development/CSS, Type=Solid.png';
  static const fileTypeDevelopmentDmgDefault = 'assets/icons/png/File type/Development/DMG, Type=Default.png';
  static const fileTypeDevelopmentDmgGray = 'assets/icons/png/File type/Development/DMG, Type=Gray.png';
  static const fileTypeDevelopmentDmgSolid = 'assets/icons/png/File type/Development/DMG, Type=Solid.png';
  static const fileTypeDevelopmentExeDefault = 'assets/icons/png/File type/Development/EXE, Type=Default.png';
  static const fileTypeDevelopmentExeGray = 'assets/icons/png/File type/Development/EXE, Type=Gray.png';
  static const fileTypeDevelopmentExeSolid = 'assets/icons/png/File type/Development/EXE, Type=Solid.png';
  static const fileTypeDevelopmentHtmlDefault = 'assets/icons/png/File type/Development/HTML, Type=Default.png';
  static const fileTypeDevelopmentHtmlGray = 'assets/icons/png/File type/Development/HTML, Type=Gray.png';
  static const fileTypeDevelopmentHtmlSolid = 'assets/icons/png/File type/Development/HTML, Type=Solid.png';
  static const fileTypeDevelopmentJavaDefault = 'assets/icons/png/File type/Development/JAVA, Type=Default.png';
  static const fileTypeDevelopmentJavaGray = 'assets/icons/png/File type/Development/JAVA, Type=Gray.png';
  static const fileTypeDevelopmentJavaSolid = 'assets/icons/png/File type/Development/JAVA, Type=Solid.png';
  static const fileTypeDevelopmentJsDefault = 'assets/icons/png/File type/Development/JS, Type=Default.png';
  static const fileTypeDevelopmentJsGray = 'assets/icons/png/File type/Development/JS, Type=Gray.png';
  static const fileTypeDevelopmentJsSolid = 'assets/icons/png/File type/Development/JS, Type=Solid.png';
  static const fileTypeDevelopmentJsonDefault = 'assets/icons/png/File type/Development/JSON, Type=Default.png';
  static const fileTypeDevelopmentJsonGray = 'assets/icons/png/File type/Development/JSON, Type=Gray.png';
  static const fileTypeDevelopmentJsonSolid = 'assets/icons/png/File type/Development/JSON, Type=Solid.png';
  static const fileTypeDevelopmentRssDefault = 'assets/icons/png/File type/Development/RSS, Type=Default.png';
  static const fileTypeDevelopmentRssGray = 'assets/icons/png/File type/Development/RSS, Type=Gray.png';
  static const fileTypeDevelopmentRssSolid = 'assets/icons/png/File type/Development/RSS, Type=Solid.png';
  static const fileTypeDevelopmentSqlDefault = 'assets/icons/png/File type/Development/SQL, Type=Default.png';
  static const fileTypeDevelopmentSqlGray = 'assets/icons/png/File type/Development/SQL, Type=Gray.png';
  static const fileTypeDevelopmentSqlSolid = 'assets/icons/png/File type/Development/SQL, Type=Solid.png';
  static const fileTypeDevelopmentXmlDefault = 'assets/icons/png/File type/Development/XML, Type=Default.png';
  static const fileTypeDevelopmentXmlGray = 'assets/icons/png/File type/Development/XML, Type=Gray.png';
  static const fileTypeDevelopmentXmlSolid = 'assets/icons/png/File type/Development/XML, Type=Solid.png';
  static const fileTypeDocumentCsvDefault = 'assets/icons/png/File type/Document/CSV, Type=Default.png';
  static const fileTypeDocumentCsvGray = 'assets/icons/png/File type/Document/CSV, Type=Gray.png';
  static const fileTypeDocumentCsvSolid = 'assets/icons/png/File type/Document/CSV, Type=Solid.png';
  static const fileTypeDocumentDocDefault = 'assets/icons/png/File type/Document/DOC, Type=Default.png';
  static const fileTypeDocumentDocGray = 'assets/icons/png/File type/Document/DOC, Type=Gray.png';
  static const fileTypeDocumentDocSolid = 'assets/icons/png/File type/Document/DOC, Type=Solid.png';
  static const fileTypeDocumentDocxDefault = 'assets/icons/png/File type/Document/DOCX, Type=Default.png';
  static const fileTypeDocumentDocxGray = 'assets/icons/png/File type/Document/DOCX, Type=Gray.png';
  static const fileTypeDocumentDocxSolid = 'assets/icons/png/File type/Document/DOCX, Type=Solid.png';
  static const fileTypeDocumentPdfDefault = 'assets/icons/png/File type/Document/PDF, Type=Default.png';
  static const fileTypeDocumentPdfGray = 'assets/icons/png/File type/Document/PDF, Type=Gray.png';
  static const fileTypeDocumentPdfSolid = 'assets/icons/png/File type/Document/PDF, Type=Solid.png';
  static const fileTypeDocumentPptDefault = 'assets/icons/png/File type/Document/PPT, Type=Default.png';
  static const fileTypeDocumentPptGray = 'assets/icons/png/File type/Document/PPT, Type=Gray.png';
  static const fileTypeDocumentPptSolid = 'assets/icons/png/File type/Document/PPT, Type=Solid.png';
  static const fileTypeDocumentPptxDefault = 'assets/icons/png/File type/Document/PPTX, Type=Default.png';
  static const fileTypeDocumentPptxGray = 'assets/icons/png/File type/Document/PPTX, Type=Gray.png';
  static const fileTypeDocumentPptxSolid = 'assets/icons/png/File type/Document/PPTX, Type=Solid.png';
  static const fileTypeDocumentTxtDefault = 'assets/icons/png/File type/Document/TXT, Type=Default.png';
  static const fileTypeDocumentTxtGray = 'assets/icons/png/File type/Document/TXT, Type=Gray.png';
  static const fileTypeDocumentTxtSolid = 'assets/icons/png/File type/Document/TXT, Type=Solid.png';
  static const fileTypeDocumentXlsDefault = 'assets/icons/png/File type/Document/XLS, Type=Default.png';
  static const fileTypeDocumentXlsGray = 'assets/icons/png/File type/Document/XLS, Type=Gray.png';
  static const fileTypeDocumentXlsSolid = 'assets/icons/png/File type/Document/XLS, Type=Solid.png';
  static const fileTypeDocumentXlsxDefault = 'assets/icons/png/File type/Document/XLSX, Type=Default.png';
  static const fileTypeDocumentXlsxGray = 'assets/icons/png/File type/Document/XLSX, Type=Gray.png';
  static const fileTypeDocumentXlsxSolid = 'assets/icons/png/File type/Document/XLSX, Type=Solid.png';
  static const fileTypeImageEpsDefault = 'assets/icons/png/File type/Image/EPS, Type=Default.png';
  static const fileTypeImageEpsGray = 'assets/icons/png/File type/Image/EPS, Type=Gray.png';
  static const fileTypeImageEpsSolid = 'assets/icons/png/File type/Image/EPS, Type=Solid.png';
  static const fileTypeImageGifDefault = 'assets/icons/png/File type/Image/GIF, Type=Default.png';
  static const fileTypeImageGifGray = 'assets/icons/png/File type/Image/GIF, Type=Gray.png';
  static const fileTypeImageGifSolid = 'assets/icons/png/File type/Image/GIF, Type=Solid.png';
  static const fileTypeImageImgDefault = 'assets/icons/png/File type/Image/IMG, Type=Default.png';
  static const fileTypeImageImgGray = 'assets/icons/png/File type/Image/IMG, Type=Gray.png';
  static const fileTypeImageImgSolid = 'assets/icons/png/File type/Image/IMG, Type=Solid.png';
  static const fileTypeImageJpegDefault = 'assets/icons/png/File type/Image/JPEG, Type=Default.png';
  static const fileTypeImageJpegGray = 'assets/icons/png/File type/Image/JPEG, Type=Gray.png';
  static const fileTypeImageJpegSolid = 'assets/icons/png/File type/Image/JPEG, Type=Solid.png';
  static const fileTypeImageJpgDefault = 'assets/icons/png/File type/Image/JPG, Type=Default.png';
  static const fileTypeImageJpgGray = 'assets/icons/png/File type/Image/JPG, Type=Gray.png';
  static const fileTypeImageJpgSolid = 'assets/icons/png/File type/Image/JPG, Type=Solid.png';
  static const fileTypeImagePngDefault = 'assets/icons/png/File type/Image/PNG, Type=Default.png';
  static const fileTypeImagePngGray = 'assets/icons/png/File type/Image/PNG, Type=Gray.png';
  static const fileTypeImagePngSolid = 'assets/icons/png/File type/Image/PNG, Type=Solid.png';
  static const fileTypeImageSvgDefault = 'assets/icons/png/File type/Image/SVG, Type=Default.png';
  static const fileTypeImageSvgGray = 'assets/icons/png/File type/Image/SVG, Type=Gray.png';
  static const fileTypeImageSvgSolid = 'assets/icons/png/File type/Image/SVG, Type=Solid.png';
  static const fileTypeImageTiffDefault = 'assets/icons/png/File type/Image/TIFF, Type=Default.png';
  static const fileTypeImageTiffGray = 'assets/icons/png/File type/Image/TIFF, Type=Gray.png';
  static const fileTypeImageTiffSolid = 'assets/icons/png/File type/Image/TIFF, Type=Solid.png';
  static const fileTypeImageWebpDefault = 'assets/icons/png/File type/Image/WebP, Type=Default.png';
  static const fileTypeImageWebpGray = 'assets/icons/png/File type/Image/WebP, Type=Gray.png';
  static const fileTypeImageWebpSolid = 'assets/icons/png/File type/Image/WebP, Type=Solid.png';
  static const fileTypeMediaAviDefault = 'assets/icons/png/File type/Media/AVI, Type=Default.png';
  static const fileTypeMediaAviGray = 'assets/icons/png/File type/Media/AVI, Type=Gray.png';
  static const fileTypeMediaAviSolid = 'assets/icons/png/File type/Media/AVI, Type=Solid.png';
  static const fileTypeMediaMkvDefault = 'assets/icons/png/File type/Media/MKV, Type=Default.png';
  static const fileTypeMediaMkvGray = 'assets/icons/png/File type/Media/MKV, Type=Gray.png';
  static const fileTypeMediaMkvSolid = 'assets/icons/png/File type/Media/MKV, Type=Solid.png';
  static const fileTypeMediaMp3Default = 'assets/icons/png/File type/Media/MP3, Type=Default.png';
  static const fileTypeMediaMp3Gray = 'assets/icons/png/File type/Media/MP3, Type=Gray.png';
  static const fileTypeMediaMp3Solid = 'assets/icons/png/File type/Media/MP3, Type=Solid.png';
  static const fileTypeMediaMp4Default = 'assets/icons/png/File type/Media/MP4, Type=Default.png';
  static const fileTypeMediaMp4Gray = 'assets/icons/png/File type/Media/MP4, Type=Gray.png';
  static const fileTypeMediaMp4Solid = 'assets/icons/png/File type/Media/MP4, Type=Solid.png';
  static const fileTypeMediaMpegDefault = 'assets/icons/png/File type/Media/MPEG, Type=Default.png';
  static const fileTypeMediaMpegGray = 'assets/icons/png/File type/Media/MPEG, Type=Gray.png';
  static const fileTypeMediaMpegSolid = 'assets/icons/png/File type/Media/MPEG, Type=Solid.png';
  static const fileTypeMediaWavDefault = 'assets/icons/png/File type/Media/WAV, Type=Default.png';
  static const fileTypeMediaWavGray = 'assets/icons/png/File type/Media/WAV, Type=Gray.png';
  static const fileTypeMediaWavSolid = 'assets/icons/png/File type/Media/WAV, Type=Solid.png';
  static const fileTypeSimpleAudioDefault = 'assets/icons/png/File type/Simple/Audio, Type=Default.png';
  static const fileTypeSimpleCodeDefault = 'assets/icons/png/File type/Simple/Code, Type=Default.png';
  static const fileTypeSimpleDocumentDefault = 'assets/icons/png/File type/Simple/Document, Type=Default.png';
  static const fileTypeSimpleEmptyDefault = 'assets/icons/png/File type/Simple/Empty, Type=Default.png';
  static const fileTypeSimpleEmptyGray = 'assets/icons/png/File type/Simple/Empty, Type=Gray.png';
  static const fileTypeSimpleEmptySolid = 'assets/icons/png/File type/Simple/Empty, Type=Solid.png';
  static const fileTypeSimpleFolderDefault = 'assets/icons/png/File type/Simple/Folder, Type=Default.png';
  static const fileTypeSimpleFolderGray = 'assets/icons/png/File type/Simple/Folder, Type=Gray.png';
  static const fileTypeSimpleFolderSolid = 'assets/icons/png/File type/Simple/Folder, Type=Solid.png';
  static const fileTypeSimpleImageDefault = 'assets/icons/png/File type/Simple/Image, Type=Default.png';
  static const fileTypeSimplePdfDefault = 'assets/icons/png/File type/Simple/PDF, Type=Default.png';
  static const fileTypeSimpleSpreadsheetDefault = 'assets/icons/png/File type/Simple/Spreadsheet, Type=Default.png';
  static const fileTypeSimpleVideo01Default = 'assets/icons/png/File type/Simple/Video 01, Type=Default.png';
  static const fileTypeSimpleVideo02Default = 'assets/icons/png/File type/Simple/Video 02, Type=Default.png';
}
